#line 43 "gibbon-gmd-lexer.l"
#define yy_create_buffer gibbon_gmd_lexer__create_buffer
#define yy_delete_buffer gibbon_gmd_lexer__delete_buffer
#define yy_flush_buffer gibbon_gmd_lexer__flush_buffer
#define yy_scan_buffer gibbon_gmd_lexer__scan_buffer
#define yy_scan_bytes gibbon_gmd_lexer__scan_bytes
#define yy_scan_string gibbon_gmd_lexer__scan_string
#define yy_switch_to_buffer gibbon_gmd_lexer__switch_to_buffer
#define yyalloc gibbon_gmd_lexer_alloc
#define yyfree gibbon_gmd_lexer_free
#define yyget_column gibbon_gmd_lexer_get_column
#define yyget_debug gibbon_gmd_lexer_get_debug
#define yyget_extra gibbon_gmd_lexer_get_extra
#define yyget_in gibbon_gmd_lexer_get_in
#define yyget_leng gibbon_gmd_lexer_get_leng
#define yyget_lineno gibbon_gmd_lexer_get_lineno
#define yyget_lval gibbon_gmd_lexer_get_lval
#define yyget_out gibbon_gmd_lexer_get_out
#define yyget_text gibbon_gmd_lexer_get_text
#define yylex gibbon_gmd_lexer_lex
#define yylex_destroy gibbon_gmd_lexer_lex_destroy
#define yylex_init gibbon_gmd_lexer_lex_init
#define yylex_init_extra gibbon_gmd_lexer_lex_init_extra
#define yypop_buffer_state gibbon_gmd_lexer_pop_buffer_state
#define yypush_buffer_state gibbon_gmd_lexer_push_buffer_state
#define yyrealloc gibbon_gmd_lexer_realloc
#define yyrestart gibbon_gmd_lexer_restart
#define yyset_column gibbon_gmd_lexer_set_column
#define yyset_debug gibbon_gmd_lexer_set_debug
#define yyset_extra gibbon_gmd_lexer_set_extra
#define yyset_in gibbon_gmd_lexer_set_in
#define yyset_lineno gibbon_gmd_lexer_set_lineno
#define yyset_lval gibbon_gmd_lexer_set_lval
#define yyset_out gibbon_gmd_lexer_set_out



#line 39 "gibbon-gmd-lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* An opaque pointer. */
#ifndef YY_TYPEDEF_YY_SCANNER_T
#define YY_TYPEDEF_YY_SCANNER_T
typedef void* yyscan_t;
#endif

/* For convenience, these vars (plus the bison vars far below)
   are macros in the reentrant scanner. */
#define yyin yyg->yyin_r
#define yyout yyg->yyout_r
#define yyextra yyg->yyextra_r
#define yyleng yyg->yyleng_r
#define yytext yyg->yytext_r
#define yylineno (YY_CURRENT_BUFFER_LVALUE->yy_bs_lineno)
#define yycolumn (YY_CURRENT_BUFFER_LVALUE->yy_bs_column)
#define yy_flex_debug yyg->yy_flex_debug_r

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yyg->yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yyg->yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin ,yyscanner )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = yyg->yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yyg->yy_c_buf_p = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yyg->yytext_ptr , yyscanner )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( yyg->yy_buffer_stack \
                          ? yyg->yy_buffer_stack[yyg->yy_buffer_stack_top] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE yyg->yy_buffer_stack[yyg->yy_buffer_stack_top]

void yyrestart (FILE *input_file ,yyscan_t yyscanner );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size ,yyscan_t yyscanner );
void yy_delete_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yy_flush_buffer (YY_BUFFER_STATE b ,yyscan_t yyscanner );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer ,yyscan_t yyscanner );
void yypop_buffer_state (yyscan_t yyscanner );

static void yyensure_buffer_stack (yyscan_t yyscanner );
static void yy_load_buffer_state (yyscan_t yyscanner );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file ,yyscan_t yyscanner );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER ,yyscanner)

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str ,yyscan_t yyscanner );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len ,yyscan_t yyscanner );

void *yyalloc (yy_size_t ,yyscan_t yyscanner );
void *yyrealloc (void *,yy_size_t ,yyscan_t yyscanner );
void yyfree (void * ,yyscan_t yyscanner );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (yyscanner); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap(yyscanner) 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

typedef int yy_state_type;

#define yytext_ptr yytext_r

static yy_state_type yy_get_previous_state (yyscan_t yyscanner );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  ,yyscan_t yyscanner);
static int yy_get_next_buffer (yyscan_t yyscanner );
static void yy_fatal_error (yyconst char msg[] ,yyscan_t yyscanner );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yyg->yytext_ptr = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	yyg->yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yyg->yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 51
#define YY_END_OF_BUFFER 52
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[253] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   27,   27,    0,    0,    0,    0,   41,   41,
        0,    0,    0,    0,    0,    0,   52,   50,    2,   48,
       48,   50,    4,   49,   50,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   42,   43,   44,   46,   46,   44,
       44,   46,    8,    8,   50,    9,    8,   50,   50,   27,
        2,   27,   27,   27,   27,   50,    2,   24,   24,   50,
       49,   30,   31,   32,   33,   41,    2,   41,   41,   41,
       11,   11,   50,   50,   50,   50,   50,   50,   18,   50,
       19,   20,    2,   48,    0,    1,    1,   49,    0,   40,

       40,   40,   40,   40,   40,   40,   40,   40,   40,   40,
       40,   40,   40,    0,    0,    8,    9,    9,    0,    0,
       27,    2,   27,   27,    1,   27,   27,    0,   24,   24,
        2,   24,    0,    1,    1,   49,    0,    0,    0,   41,
        2,   41,    1,   41,   11,    0,    0,    0,    0,    0,
        0,   19,   19,    1,    3,   40,   40,   40,   40,   40,
       40,   40,   40,   40,   40,   40,   40,   40,   40,    0,
        0,    9,    0,    0,   27,   24,    1,   31,    0,   33,
        0,    0,    0,    0,    0,    0,   40,   40,   35,   10,
       40,   40,   29,   40,   22,   40,   40,   28,   25,   36,

        0,    0,    0,    0,   27,   32,   16,   13,    0,    0,
        0,   15,   40,   40,   40,   40,   40,   40,   40,   47,
       45,    7,    0,   27,    0,    0,    0,   39,   34,    5,
       40,   21,   38,   37,    0,   27,    0,   12,   14,   40,
        0,   27,    0,   23,    0,   26,    0,    6,   26,    0,
       17,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    1,    5,    1,    1,    1,    1,    1,
        1,    1,    6,    1,    7,    1,    8,    9,   10,   11,
       11,   11,   11,   11,   11,   11,   11,   12,    1,    1,
        1,    1,    1,    1,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   29,
        1,    1,    1,    1,   29,    1,   38,   39,   40,   41,

       42,   43,   44,   45,   46,   47,   48,   49,   50,   51,
       52,   53,   29,   54,   55,   56,   57,   58,   59,   36,
       60,   29,   61,    1,   62,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[63] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    3,    3,
        3,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        1,    1
    } ;

static yyconst flex_int16_t yy_base[265] =
    {   0,
        0,   43,   87,    0,   11,   22,  148,    0,   54,   65,
      206,  262,  161,  187,  219,  231,  313,    0,  241,  272,
      371,    0,  289,  299,  426,  487,  318,  680,  253,  680,
      215,   14,  680,   19,   10,   40,    0,  151,  141,  263,
      133,  137,  326,  155,  680,  680,   27,   30,  145,  680,
      154,  680,  680,  211,   32,   72,  680,  161,  169,    0,
      217,  209,   75,   75,   19,  222,  245,  680,  234,  250,
      275,  680,  275,  262,  288,    0,  202,  174,  255,  251,
      680,  170,  123,  286,  298,  289,  302,  149,  680,  259,
      315,  680,  165,  680,  293,  680,  325,  335,  314,    0,

      322,  314,  311,  329,  340,  352,  327,  356,  344,  362,
      364,  365,  367,  384,  377,  680,  395,  409,  374,  392,
        0,  432,  347,  331,  353,  429,  429,  404,  680,  440,
      446,  680,  442,  680,  448,  450,  425,  431,  439,    0,
       69,  459,  461,  459,  680,  444,  459,  440,  455,  451,
      441,  475,  495,  680,  680,  470,  488,  479,  491,  490,
      497,  494,  477,  490,  498,  495,  493,  501,  502,  505,
      490,  514,  509,  507,  495,  680,  680,  680,  514,  680,
      522,  530,   44,  522,  520,  526,  527,  533,    0,    0,
      527,  528,    0,  544,    0,  547,  544,    0,    0,    0,

      542,  549,  521,  542,  550,  680,  680,  680,  553,  539,
      558,  680,  546,  559,  559,  564,  559,  564,  571,  680,
      680,  680,  577,  572,  576,  574,  575,    0,    0,    0,
      580,    0,    0,    0,  577,  581,  579,  680,  680,  588,
      598,  600,  603,    0,  602,   10,  595,  680,    6,  604,
      680,  680,  646,  649,  652,  655,  658,    3,  661,  664,
      667,  670,  673,  676
    } ;

static yyconst flex_int16_t yy_def[265] =
    {   0,
      253,  253,  252,    3,  253,  253,  253,    7,  253,  253,
      253,  253,  254,  254,  255,  255,    7,   17,  256,  256,
      253,   21,  253,  253,  253,  253,  252,  252,  252,  252,
      252,  257,  252,  252,  252,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  259,
      259,  259,  260,  259,  259,  261,  261,  252,  261,  262,
      261,  252,  252,  252,  252,  263,  263,  263,  264,  263,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  257,  252,  257,  252,  252,  258,

      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,
      258,  258,  258,  252,  252,  252,  252,  252,  252,  252,
      259,  259,  259,  260,  260,  259,  259,  261,  252,  261,
      261,  252,  262,  252,  262,  261,  252,  252,  252,  263,
      263,  264,  264,  263,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  258,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  252,
      252,  252,  252,  252,  259,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  258,  258,  258,  258,
      258,  258,  258,  258,  258,  258,  258,  258,  258,  258,

      252,  252,  252,  252,  259,  252,  252,  252,  252,  252,
      252,  252,  258,  258,  258,  258,  258,  258,  258,  252,
      252,  252,  252,  259,  252,  252,  252,  258,  258,  258,
      258,  258,  258,  258,  252,  259,  252,  252,  252,  258,
      252,  259,  252,  258,  252,  259,  252,  252,  259,  252,
      252,    0,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252
    } ;

static yyconst flex_int16_t yy_nxt[743] =
    {   0,
      252,   29,   30,   31,   32,  100,   33,  249,   34,   34,
       34,  249,   29,   30,   31,   32,   96,   97,   35,   34,
       34,   34,   45,   29,   30,   31,   32,   98,   98,   98,
       34,   34,   34,   45,   99,   98,   98,   98,   98,   98,
       98,  117,  117,   35,   29,   30,   31,   32,  127,   33,
      209,   34,   34,   34,  101,   29,   53,   54,   32,   99,
       55,   35,   34,   56,   56,   57,   29,   53,   54,   32,
      141,   55,  127,   34,   56,   56,   57,   96,  125,  101,
      118,  118,  118,  126,  126,  126,   35,   28,   29,   30,
       31,   32,   28,   28,   28,   34,   34,   34,   28,   36,

       37,   37,   38,   37,   37,   39,   37,   37,   37,   37,
       40,   41,   37,   37,   42,   37,   43,   37,   44,   37,
       37,   37,   37,   37,   36,   37,   37,   38,   37,   37,
       39,   37,   37,   37,   37,   40,   41,   37,   37,   42,
       43,   37,   44,   37,   37,   37,   37,   28,   28,   29,
       30,   31,   32,  104,   46,  146,   47,   48,   34,  107,
      108,   49,   61,   30,   62,   63,   93,  113,  114,   64,
       64,   64,  145,  115,   50,   65,   94,  102,  104,  146,
      103,  151,   51,   52,  107,  108,   49,  119,   61,   30,
       62,   63,  113,  114,  120,   64,   64,   64,  115,   50,

       65,   65,  102,  141,  103,  151,   51,   29,   30,   31,
       32,   94,  119,  116,   34,   34,   34,   94,  122,  120,
       67,   68,   69,   70,  129,  130,   65,   71,   71,   71,
       58,  123,   67,   68,   69,   70,  132,  130,   59,   71,
       71,   71,   77,   30,   78,   79,  131,  129,  130,   80,
       80,   80,  134,  135,   93,   58,  123,   96,  143,  144,
      144,  144,   59,   29,   30,   31,   32,  152,  152,  152,
       34,   34,   34,   77,   30,   78,   79,  129,  130,  105,
       80,   80,   80,  136,  136,  136,   58,  137,  138,  106,
       29,   30,   31,   32,   59,   96,   97,   34,   34,   34,

       29,   30,   31,   32,  105,  139,  147,   34,   34,   34,
      148,   58,  137,  138,  106,  149,  150,  252,   59,   72,
       72,   34,   34,  153,  153,  153,   73,  154,   97,  155,
      139,  147,   74,   96,  125,  148,  156,  158,  109,   75,
      149,  150,  110,   98,   98,   98,  157,   28,   28,   89,
      252,   73,  111,  159,  155,  154,  125,   74,  112,   89,
      162,  156,  158,  109,   75,  160,  161,  110,  163,  164,
      157,   28,   29,   81,   82,   32,  127,  111,  159,   34,
       34,   34,  112,  165,  162,   83,   84,  167,  168,  169,
      160,  161,  166,  163,  164,   85,  170,  171,   86,  173,

      127,   87,   88,  172,  172,  172,  129,  130,  165,  252,
       83,   84,  167,  168,  169,  174,  166,  118,  118,  118,
       85,  170,  171,   86,  173,   87,   88,   29,   30,   31,
       32,   90,   90,  122,   91,   91,   91,  126,  126,  126,
      174,  175,  176,  130,  134,  135,  123,  131,  129,  130,
      177,  135,  129,  130,  178,  179,  180,  181,  136,  136,
      136,   96,  143,  154,  143,  252,  175,  144,  144,  144,
      186,  123,  252,  182,  252,  184,  183,  185,  178,  252,
      179,  180,  181,  152,  152,  152,  187,   92,   29,   30,
       31,   32,   90,   90,  186,   91,   91,   91,  182,  183,

      184,  188,  185,  153,  153,  153,  189,  190,  191,  192,
      193,  187,  195,  194,  196,  197,  198,  199,  200,  201,
      252,  202,  172,  172,  172,  203,  188,  204,  252,  205,
      206,  189,  190,  191,  192,  193,  194,  195,  207,  196,
      197,  198,  199,  200,  201,  202,  208,  210,   92,  211,
      203,  212,  204,  205,  213,  206,  214,  222,  215,  216,
      217,  218,  219,  207,  220,  221,  223,  224,  225,  252,
      226,  208,  210,  211,  227,  229,  212,  228,  230,  213,
      222,  214,  215,  216,  231,  217,  218,  219,  232,  220,
      221,  223,  224,  225,  226,  233,  234,  235,  236,  227,

      229,  228,  237,  230,  238,  239,  240,  252,  241,  231,
      242,  243,  232,  244,  245,  246,  247,  248,  250,  233,
      251,  234,  235,  236,  252,  252,  252,  237,  238,  239,
      252,  240,  241,  252,  242,  243,  252,  252,  244,  245,
      246,  247,  248,  250,  252,  251,   28,   28,   28,   60,
       60,   60,   66,   66,   66,   76,   76,   76,   95,   95,
       95,  121,  252,  121,  124,  124,  124,  128,  128,  128,
      133,  133,  133,  140,  252,  140,  142,  142,  142,   27,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252
    } ;

static yyconst flex_int16_t yy_chk[743] =
    {   0,
        0,    1,    1,    1,    1,  258,    1,  249,    1,    1,
        1,  246,    5,    5,    5,    5,   32,   32,    1,    5,
        5,    5,    5,    6,    6,    6,    6,   34,   34,   34,
        6,    6,    6,    6,   35,   47,   47,   47,   48,   48,
       48,   55,   55,    1,    2,    2,    2,    2,   65,    2,
      183,    2,    2,    2,   36,    9,    9,    9,    9,   35,
        9,    2,    9,    9,    9,    9,   10,   10,   10,   10,
      141,   10,   65,   10,   10,   10,   10,   63,   63,   36,
       56,   56,   56,   64,   64,   64,    2,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    7,
        7,    7,    7,   39,    7,   83,    7,    7,    7,   41,
       42,    7,   13,   13,   13,   13,   93,   44,   49,   13,
       13,   13,   82,   51,    7,   13,   78,   38,   39,   83,
       38,   88,    7,    7,   41,   42,    7,   58,   14,   14,
       14,   14,   44,   49,   59,   14,   14,   14,   51,    7,

       13,   14,   38,   77,   38,   88,    7,   11,   11,   11,
       11,   62,   58,   54,   11,   11,   11,   31,   61,   59,
       15,   15,   15,   15,   66,   66,   14,   15,   15,   15,
       11,   61,   16,   16,   16,   16,   69,   69,   11,   16,
       16,   16,   19,   19,   19,   19,   67,   67,   67,   19,
       19,   19,   70,   70,   29,   11,   61,   79,   79,   80,
       80,   80,   11,   12,   12,   12,   12,   90,   90,   90,
       12,   12,   12,   20,   20,   20,   20,   71,   71,   40,
       20,   20,   20,   71,   71,   71,   12,   73,   74,   40,
       23,   23,   23,   23,   12,   95,   95,   23,   23,   23,

       24,   24,   24,   24,   40,   75,   84,   24,   24,   24,
       85,   12,   73,   74,   40,   86,   87,   27,   12,   17,
       17,   17,   17,   91,   91,   91,   17,   97,   97,   99,
       75,   84,   17,  124,  124,   85,  101,  103,   43,   17,
       86,   87,   43,   98,   98,   98,  102,   17,   17,   23,
        0,   17,   43,  104,   99,  125,  125,   17,   43,   24,
      107,  101,  103,   43,   17,  105,  106,   43,  108,  109,
      102,   17,   21,   21,   21,   21,  123,   43,  104,   21,
       21,   21,   43,  110,  107,   21,   21,  111,  112,  113,
      105,  106,  110,  108,  109,   21,  114,  115,   21,  119,

      123,   21,   21,  117,  117,  117,  128,  128,  110,    0,
       21,   21,  111,  112,  113,  120,  110,  118,  118,  118,
       21,  114,  115,   21,  119,   21,   21,   25,   25,   25,
       25,   25,   25,  122,   25,   25,   25,  126,  126,  126,
      120,  127,  130,  130,  133,  133,  122,  131,  131,  131,
      135,  135,  136,  136,  137,  138,  139,  146,  136,  136,
      136,  142,  142,  143,  143,    0,  127,  144,  144,  144,
      151,  122,    0,  147,    0,  149,  148,  150,  137,    0,
      138,  139,  146,  152,  152,  152,  156,   25,   26,   26,
       26,   26,   26,   26,  151,   26,   26,   26,  147,  148,

      149,  157,  150,  153,  153,  153,  158,  159,  160,  161,
      162,  156,  164,  163,  165,  166,  167,  168,  169,  170,
        0,  171,  172,  172,  172,  173,  157,  174,    0,  175,
      179,  158,  159,  160,  161,  162,  163,  164,  181,  165,
      166,  167,  168,  169,  170,  171,  182,  184,   26,  185,
      173,  186,  174,  175,  187,  179,  188,  203,  191,  192,
      194,  196,  197,  181,  201,  202,  204,  205,  209,    0,
      210,  182,  184,  185,  211,  214,  186,  213,  215,  187,
      203,  188,  191,  192,  216,  194,  196,  197,  217,  201,
      202,  204,  205,  209,  210,  218,  219,  223,  224,  211,

      214,  213,  225,  215,  226,  227,  231,    0,  235,  216,
      236,  237,  217,  240,  241,  242,  243,  245,  247,  218,
      250,  219,  223,  224,    0,    0,    0,  225,  226,  227,
        0,  231,  235,    0,  236,  237,    0,    0,  240,  241,
      242,  243,  245,  247,    0,  250,  253,  253,  253,  254,
      254,  254,  255,  255,  255,  256,  256,  256,  257,  257,
      257,  259,    0,  259,  260,  260,  260,  261,  261,  261,
      262,  262,  262,  263,    0,  263,  264,  264,  264,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,

      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252,  252,  252,  252,  252,  252,  252,  252,  252,
      252,  252
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[52] =
    {   0,
1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "gibbon-gmd-lexer.l"
/*
 * This file is part of gibbon.
 * Gibbon is a Gtk+ frontend for the First Internet Backgammon Server FIBS.
 * Copyright (C) 2009-2012 Guido Flohr, http://guido-flohr.net/.
 *
 * gibbon is free software: you can redistribute it and/or modify 
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * gibbon is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with gibbon.  If not, see <http://www.gnu.org/licenses/>.
 */
/*
 * Lexical scanner for the internal format of Gibbon.
 */
#line 25 "gibbon-gmd-lexer.l"
#ifdef HAVE_CONFIG_H
# include "config.h"
#endif

#include "gibbon-util.h"

#include <glib.h>
#include <glib/gi18n.h>

#include "gibbon-gmd-parser.h"
#include "gibbon-gmd-reader-priv.h"

#define alloc_name(s) gibbon_gmd_reader_alloc_name(		\
	gibbon_gmd_lexer_get_extra(yyscanner), s)
		

#line 79 "gibbon-gmd-lexer.l"
extern void gibbon_gmd_reader_yyerror (void *scanner, const gchar *msg);
#define yyerror(scanner, msg) gibbon_gmd_reader_yyerror (scanner, msg)
#define YY_NO_INPUT 1
/* %option debug */












#line 794 "gibbon-gmd-lexer.c"

#define INITIAL 0
#define OPCODE 1
#define SCOLON 2
#define SCOLOR 3
#define STIMESTAMP 4
#define SLENGTH 5
#define SRULE 6
#define SNAME 7
#define SMOVE 8
#define EAT_UP 9
#define SGAME 10
#define SLBRACE 11
#define STUPLE 12

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

/* Holds the entire state of the reentrant scanner. */
struct yyguts_t
    {

    /* User-defined. Not touched by flex. */
    YY_EXTRA_TYPE yyextra_r;

    /* The rest are the same as the globals declared in the non-reentrant scanner. */
    FILE *yyin_r, *yyout_r;
    size_t yy_buffer_stack_top; /**< index of top of stack. */
    size_t yy_buffer_stack_max; /**< capacity of stack. */
    YY_BUFFER_STATE * yy_buffer_stack; /**< Stack as an array. */
    char yy_hold_char;
    yy_size_t yy_n_chars;
    yy_size_t yyleng_r;
    char *yy_c_buf_p;
    int yy_init;
    int yy_start;
    int yy_did_buffer_switch_on_eof;
    int yy_start_stack_ptr;
    int yy_start_stack_depth;
    int *yy_start_stack;
    yy_state_type yy_last_accepting_state;
    char* yy_last_accepting_cpos;

    int yylineno_r;
    int yy_flex_debug_r;

    char *yytext_r;
    int yy_more_flag;
    int yy_more_len;

    YYSTYPE * yylval_r;

    }; /* end struct yyguts_t */

static int yy_init_globals (yyscan_t yyscanner );

    /* This must go here because YYSTYPE and YYLTYPE are included
     * from bison output in section 1.*/
    #    define yylval yyg->yylval_r
    
int yylex_init (yyscan_t* scanner);

int yylex_init_extra (YY_EXTRA_TYPE user_defined,yyscan_t* scanner);

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (yyscan_t yyscanner );

int yyget_debug (yyscan_t yyscanner );

void yyset_debug (int debug_flag ,yyscan_t yyscanner );

YY_EXTRA_TYPE yyget_extra (yyscan_t yyscanner );

void yyset_extra (YY_EXTRA_TYPE user_defined ,yyscan_t yyscanner );

FILE *yyget_in (yyscan_t yyscanner );

void yyset_in  (FILE * in_str ,yyscan_t yyscanner );

FILE *yyget_out (yyscan_t yyscanner );

void yyset_out  (FILE * out_str ,yyscan_t yyscanner );

yy_size_t yyget_leng (yyscan_t yyscanner );

char *yyget_text (yyscan_t yyscanner );

int yyget_lineno (yyscan_t yyscanner );

void yyset_lineno (int line_number ,yyscan_t yyscanner );

int yyget_column  (yyscan_t yyscanner );

void yyset_column (int column_no ,yyscan_t yyscanner );

YYSTYPE * yyget_lval (yyscan_t yyscanner );

void yyset_lval (YYSTYPE * yylval_param ,yyscan_t yyscanner );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (yyscan_t yyscanner );
#else
extern int yywrap (yyscan_t yyscanner );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int ,yyscan_t yyscanner);
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * ,yyscan_t yyscanner);
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (yyscan_t yyscanner );
#else
static int input (yyscan_t yyscanner );
#endif

#endif

    static void yy_push_state (int new_state ,yyscan_t yyscanner);
    
    static void yy_pop_state (yyscan_t yyscanner );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg , yyscanner)
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex \
               (YYSTYPE * yylval_param ,yyscan_t yyscanner);

#define YY_DECL int yylex \
               (YYSTYPE * yylval_param , yyscan_t yyscanner)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

#line 110 "gibbon-gmd-lexer.l"


  /***************************************************************************
   * General rules, valid for all scanner states.                            *
   ***************************************************************************/
   
  /* Ignore comments.  */
#line 1053 "gibbon-gmd-lexer.c"

    yylval = yylval_param;

	if ( !yyg->yy_init )
		{
		yyg->yy_init = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yyg->yy_start )
			yyg->yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack (yyscanner);
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
		}

		yy_load_buffer_state(yyscanner );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yyg->yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yyg->yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yyg->yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yyg->yy_last_accepting_state = yy_current_state;
				yyg->yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 253 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 680 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yyg->yy_hold_char;
			yy_cp = yyg->yy_last_accepting_cpos;
			yy_current_state = yyg->yy_last_accepting_state;
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 117 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
	}
	YY_BREAK
/* Ignore all whitespace.  */
case 2:
YY_RULE_SETUP
#line 121 "gibbon-gmd-lexer.l"
;
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 123 "gibbon-gmd-lexer.l"
{
		/* The file magic is case-sensitive! */
		if ('G' == yytext[0] && 'M' == yytext[1] && 'D' == yytext[2])
	        	return MAGIC;
	        return yytext[0];
	}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 129 "gibbon-gmd-lexer.l"
return HYPHEN;
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 131 "gibbon-gmd-lexer.l"
{
		BEGIN (SLENGTH);
		yy_push_state (SCOLON, yyscanner);
		return LENGTH;
	}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 136 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		((struct yyguts_t *) yyscanner)->yylval_r->num = -1;
		return POSITIVE;
	}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 141 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		((struct yyguts_t *) yyscanner)->yylval_r->num = -1;
		return POSITIVE;
	}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 147 "gibbon-gmd-lexer.l"
{
		yy_pop_state (yyscanner);
		yyless (0);
		((struct yyguts_t *) yyscanner)->yylval_r->num = G_MININT64;
		return POSITIVE;
	}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 153 "gibbon-gmd-lexer.l"
{
        	((struct yyguts_t *) yyscanner)->yylval_r->num 
        		= (gint64) g_ascii_strtoll (yytext, NULL, 10);
        	yy_pop_state (yyscanner);
        	return POSITIVE;
        }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 160 "gibbon-gmd-lexer.l"
{
                yy_push_state (SGAME, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		return GAME;
	}
	YY_BREAK
case 11:
/* rule 11 can match eol */
YY_RULE_SETUP
#line 166 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
	}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 170 "gibbon-gmd-lexer.l"
{
		yy_push_state (SLBRACE, yyscanner);
		return POINTS;
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 175 "gibbon-gmd-lexer.l"
{
		yy_push_state (SLBRACE, yyscanner);
		return DICE;
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 180 "gibbon-gmd-lexer.l"
{
		yy_push_state (SLBRACE, yyscanner);
		return SCORES;
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 185 "gibbon-gmd-lexer.l"
{
		yy_push_state (SLBRACE, yyscanner);
		return TURN;
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 190 "gibbon-gmd-lexer.l"
{
		yy_push_state (SLBRACE, yyscanner);
		return CUBE;
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 195 "gibbon-gmd-lexer.l"
{
		yy_push_state (SLBRACE, yyscanner);
		return MAY_DOUBLE;
}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 200 "gibbon-gmd-lexer.l"
{
		yy_push_state (STUPLE, yyscanner);
		return LBRACE;
}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 205 "gibbon-gmd-lexer.l"
{
		((struct yyguts_t *) yyscanner)->yylval_r->num 
			= (gint) g_ascii_strtoll (yytext, NULL, 10);
		return INTEGER;
	}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 211 "gibbon-gmd-lexer.l"
{
		yy_pop_state (yyscanner);
		BEGIN (SGAME);
		return RBRACE;
	}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 217 "gibbon-gmd-lexer.l"
{
		BEGIN (SNAME);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (SCOLOR, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		return PLAYER;
	}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 224 "gibbon-gmd-lexer.l"
{
		BEGIN (SNAME);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (SCOLOR, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		return RANK;
	}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 231 "gibbon-gmd-lexer.l"
{
		BEGIN (SNAME);
		yy_push_state (SCOLON, yyscanner);
		return LOCATION;
	}
	YY_BREAK
case 24:
/* rule 24 can match eol */
YY_RULE_SETUP
#line 236 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		((struct yyguts_t *) yyscanner)->yylval_r->name 
			= alloc_name (gibbon_trim (yytext));
		return NAME;
	}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 243 "gibbon-gmd-lexer.l"
{
		BEGIN (SRULE);
		yy_push_state (SCOLON, yyscanner);
		return RULE;
	}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 248 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		return CRAWFORD;
	}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 252 "gibbon-gmd-lexer.l"
{
		gchar *msg = g_strdup_printf (_("warning: unknown rule `%s'"), 
		                              gibbon_trim (yytext));
		yyerror (yyscanner, msg);
		g_free (msg);

		BEGIN (OPCODE);
		return UNKNOWN;
	}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 262 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (STIMESTAMP, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (SCOLOR, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		return ROLL;
	}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 272 "gibbon-gmd-lexer.l"
{
		BEGIN (SMOVE);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (STIMESTAMP, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (SCOLOR, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		return MOVE;
	}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 281 "gibbon-gmd-lexer.l"
{
		return SLASH;
	}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 284 "gibbon-gmd-lexer.l"
{
		return BAR;
	}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 287 "gibbon-gmd-lexer.l"
{
		return HOME;
	}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 290 "gibbon-gmd-lexer.l"
{
		return HOME;
	}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 294 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		yy_push_state (STIMESTAMP, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (SCOLOR, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		return DOUBLE;
	}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 303 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		yy_push_state (STIMESTAMP, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (SCOLOR, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		return DROP;
	}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 312 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		yy_push_state (STIMESTAMP, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (SCOLOR, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		return TAKE;
	}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 321 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (STIMESTAMP, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (SCOLOR, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		return RESIGN;
	}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 331 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		yy_push_state (STIMESTAMP, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (SCOLOR, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		return REJ;
	}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 340 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		yy_push_state (STIMESTAMP, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		yy_push_state (SCOLOR, yyscanner);
		yy_push_state (SCOLON, yyscanner);
		return ACCEPT;
	}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 349 "gibbon-gmd-lexer.l"
{
		gchar *msg = g_strdup_printf (_("warning: unknown opcode `%s'"), 
		                              yytext);
		yyerror (yyscanner, msg);
		g_free (msg);
		BEGIN (EAT_UP);
		yy_push_state (SCOLON, yyscanner);
		return UNKNOWN;
	}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 359 "gibbon-gmd-lexer.l"
{
		BEGIN (OPCODE);
		return GARBAGE;
	}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 364 "gibbon-gmd-lexer.l"
{
		yy_pop_state (yyscanner);
		return COLON;
	}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 369 "gibbon-gmd-lexer.l"
{
		yy_pop_state (yyscanner);
		return NO_COLOR;
	}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 373 "gibbon-gmd-lexer.l"
{
		yy_pop_state (yyscanner);
		return WHITE;
	}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 377 "gibbon-gmd-lexer.l"
{
		yy_pop_state (yyscanner);
		return WHITE;
	}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 381 "gibbon-gmd-lexer.l"
{
		yy_pop_state (yyscanner);
		return BLACK;
	}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 385 "gibbon-gmd-lexer.l"
{
		yy_pop_state (yyscanner);
		return BLACK;
	}
	YY_BREAK
case 48:
/* rule 48 can match eol */
YY_RULE_SETUP
#line 390 "gibbon-gmd-lexer.l"
BEGIN (OPCODE);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 392 "gibbon-gmd-lexer.l"
{
		((struct yyguts_t *) yyscanner)->yylval_r->num 
			= (gint) g_ascii_strtoull (yytext, NULL, 10);
		return POSITIVE;
	}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 398 "gibbon-gmd-lexer.l"
return yytext[0];
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 399 "gibbon-gmd-lexer.l"
ECHO;
	YY_BREAK
#line 1611 "gibbon-gmd-lexer.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(OPCODE):
case YY_STATE_EOF(SCOLON):
case YY_STATE_EOF(SCOLOR):
case YY_STATE_EOF(STIMESTAMP):
case YY_STATE_EOF(SLENGTH):
case YY_STATE_EOF(SRULE):
case YY_STATE_EOF(SNAME):
case YY_STATE_EOF(SMOVE):
case YY_STATE_EOF(EAT_UP):
case YY_STATE_EOF(SGAME):
case YY_STATE_EOF(SLBRACE):
case YY_STATE_EOF(STUPLE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yyg->yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yyg->yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yyg->yy_c_buf_p <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yyg->yy_c_buf_p = yyg->yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state( yyscanner );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state , yyscanner);

			yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yyg->yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yyg->yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer( yyscanner ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yyg->yy_did_buffer_switch_on_eof = 0;

				if ( yywrap(yyscanner ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yyg->yy_c_buf_p = yyg->yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yyg->yy_c_buf_p =
					yyg->yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yyg->yy_c_buf_p =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars];

				yy_current_state = yy_get_previous_state( yyscanner );

				yy_cp = yyg->yy_c_buf_p;
				yy_bp = yyg->yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = yyg->yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yyg->yy_c_buf_p > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yyg->yy_c_buf_p - yyg->yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yyg->yy_c_buf_p - yyg->yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) (yyg->yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2 ,yyscanner );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yyg->yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			yyg->yy_n_chars, num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	if ( yyg->yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  ,yyscanner);
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) (yyg->yy_n_chars + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = yyg->yy_n_chars + number_to_move + (yyg->yy_n_chars >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size ,yyscanner );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	yyg->yy_n_chars += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yyg->yytext_ptr = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (yyscan_t yyscanner)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_current_state = yyg->yy_start;

	for ( yy_cp = yyg->yytext_ptr + YY_MORE_ADJ; yy_cp < yyg->yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yyg->yy_last_accepting_state = yy_current_state;
			yyg->yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 253 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state , yyscan_t yyscanner)
{
	register int yy_is_jam;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner; /* This var may be unused depending upon options. */
	register char *yy_cp = yyg->yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yyg->yy_last_accepting_state = yy_current_state;
		yyg->yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 253 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 252);

	(void)yyg;
	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (yyscan_t yyscanner)
#else
    static int input  (yyscan_t yyscanner)
#endif

{
	int c;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	*yyg->yy_c_buf_p = yyg->yy_hold_char;

	if ( *yyg->yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yyg->yy_c_buf_p < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[yyg->yy_n_chars] )
			/* This was really a NUL. */
			*yyg->yy_c_buf_p = '\0';

		else
			{ /* need more input */
			yy_size_t offset = yyg->yy_c_buf_p - yyg->yytext_ptr;
			++yyg->yy_c_buf_p;

			switch ( yy_get_next_buffer( yyscanner ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin ,yyscanner);

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(yyscanner ) )
						return EOF;

					if ( ! yyg->yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput(yyscanner);
#else
					return input(yyscanner);
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yyg->yy_c_buf_p = yyg->yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yyg->yy_c_buf_p;	/* cast for 8-bit char's */
	*yyg->yy_c_buf_p = '\0';	/* preserve yytext */
	yyg->yy_hold_char = *++yyg->yy_c_buf_p;

	if ( c == '\n' )
		   
    do{ yylineno++;
        yycolumn=0;
    }while(0)
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * @param yyscanner The scanner object.
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack (yyscanner);
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE ,yyscanner);
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file ,yyscanner);
	yy_load_buffer_state(yyscanner );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * @param yyscanner The scanner object.
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack (yyscanner);
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(yyscanner );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yyg->yy_did_buffer_switch_on_eof = 1;
}

static void yy_load_buffer_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	yyg->yy_n_chars = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	yyg->yytext_ptr = yyg->yy_c_buf_p = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	yyg->yy_hold_char = *yyg->yy_c_buf_p;
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * @param yyscanner The scanner object.
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2 ,yyscanner );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file ,yyscanner);

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * @param yyscanner The scanner object.
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf ,yyscanner );

	yyfree((void *) b ,yyscanner );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file , yyscan_t yyscanner)

{
	int oerrno = errno;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	yy_flush_buffer(b ,yyscanner);

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * @param yyscanner The scanner object.
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(yyscanner );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  @param yyscanner The scanner object.
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack(yyscanner);

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*yyg->yy_c_buf_p = yyg->yy_hold_char;
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = yyg->yy_c_buf_p;
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = yyg->yy_n_chars;
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		yyg->yy_buffer_stack_top++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(yyscanner );
	yyg->yy_did_buffer_switch_on_eof = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  @param yyscanner The scanner object.
 */
void yypop_buffer_state (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner);
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if (yyg->yy_buffer_stack_top > 0)
		--yyg->yy_buffer_stack_top;

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(yyscanner );
		yyg->yy_did_buffer_switch_on_eof = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (yyscan_t yyscanner)
{
	yy_size_t num_to_alloc;
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

	if (!yyg->yy_buffer_stack) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset(yyg->yy_buffer_stack, 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		yyg->yy_buffer_stack_max = num_to_alloc;
		yyg->yy_buffer_stack_top = 0;
		return;
	}

	if (yyg->yy_buffer_stack_top >= (yyg->yy_buffer_stack_max) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = yyg->yy_buffer_stack_max + grow_size;
		yyg->yy_buffer_stack = (struct yy_buffer_state**)yyrealloc
								(yyg->yy_buffer_stack,
								num_to_alloc * sizeof(struct yy_buffer_state*)
								, yyscanner);
		if ( ! yyg->yy_buffer_stack )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset(yyg->yy_buffer_stack + yyg->yy_buffer_stack_max, 0, grow_size * sizeof(struct yy_buffer_state*));
		yyg->yy_buffer_stack_max = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state ) ,yyscanner );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b ,yyscanner );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr , yyscan_t yyscanner)
{
    
	return yy_scan_bytes(yystr,strlen(yystr) ,yyscanner);
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * @param yyscanner The scanner object.
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len , yyscan_t yyscanner)
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n ,yyscanner );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n ,yyscanner);
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( yyg->yy_start_stack_ptr >= yyg->yy_start_stack_depth )
		{
		yy_size_t new_size;

		yyg->yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yyg->yy_start_stack_depth * sizeof( int );

		if ( ! yyg->yy_start_stack )
			yyg->yy_start_stack = (int *) yyalloc(new_size ,yyscanner );

		else
			yyg->yy_start_stack = (int *) yyrealloc((void *) yyg->yy_start_stack,new_size ,yyscanner );

		if ( ! yyg->yy_start_stack )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	yyg->yy_start_stack[yyg->yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
	if ( --yyg->yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yyg->yy_start_stack[yyg->yy_start_stack_ptr]);
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg , yyscan_t yyscanner)
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = yyg->yy_hold_char; \
		yyg->yy_c_buf_p = yytext + yyless_macro_arg; \
		yyg->yy_hold_char = *yyg->yy_c_buf_p; \
		*yyg->yy_c_buf_p = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the user-defined data for this scanner.
 * @param yyscanner The scanner object.
 */
YY_EXTRA_TYPE yyget_extra  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyextra;
}

/** Get the current line number.
 * @param yyscanner The scanner object.
 */
int yyget_lineno  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yylineno;
}

/** Get the current column number.
 * @param yyscanner The scanner object.
 */
int yyget_column  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    
        if (! YY_CURRENT_BUFFER)
            return 0;
    
    return yycolumn;
}

/** Get the input stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_in  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyin;
}

/** Get the output stream.
 * @param yyscanner The scanner object.
 */
FILE *yyget_out  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyout;
}

/** Get the length of the current token.
 * @param yyscanner The scanner object.
 */
yy_size_t yyget_leng  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yyleng;
}

/** Get the current token.
 * @param yyscanner The scanner object.
 */

char *yyget_text  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yytext;
}

/** Set the user-defined data. This data is never touched by the scanner.
 * @param user_defined The data to be associated with this scanner.
 * @param yyscanner The scanner object.
 */
void yyset_extra (YY_EXTRA_TYPE  user_defined , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyextra = user_defined ;
}

/** Set the current line number.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_lineno (int  line_number , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* lineno is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_lineno called with no buffer" );
    
    yylineno = line_number;
}

/** Set the current column.
 * @param line_number
 * @param yyscanner The scanner object.
 */
void yyset_column (int  column_no , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

        /* column is only valid if an input buffer exists. */
        if (! YY_CURRENT_BUFFER )
           YY_FATAL_ERROR( "yyset_column called with no buffer" );
    
    yycolumn = column_no;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * @param yyscanner The scanner object.
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyin = in_str ;
}

void yyset_out (FILE *  out_str , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yyout = out_str ;
}

int yyget_debug  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yy_flex_debug;
}

void yyset_debug (int  bdebug , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yy_flex_debug = bdebug ;
}

/* Accessor methods for yylval and yylloc */

YYSTYPE * yyget_lval  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    return yylval;
}

void yyset_lval (YYSTYPE *  yylval_param , yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    yylval = yylval_param;
}

/* User-visible API */

/* yylex_init is special because it creates the scanner itself, so it is
 * the ONLY reentrant function that doesn't take the scanner as the last argument.
 * That's why we explicitly handle the declaration, instead of using our macros.
 */

int yylex_init(yyscan_t* ptr_yy_globals)

{
    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }

    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), NULL );

    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }

    /* By setting to 0xAA, we expose bugs in yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));

    return yy_init_globals ( *ptr_yy_globals );
}

/* yylex_init_extra has the same functionality as yylex_init, but follows the
 * convention of taking the scanner as the last argument. Note however, that
 * this is a *pointer* to a scanner, as it will be allocated by this call (and
 * is the reason, too, why this function also must handle its own declaration).
 * The user defined value in the first argument will be available to yyalloc in
 * the yyextra field.
 */

int yylex_init_extra(YY_EXTRA_TYPE yy_user_defined,yyscan_t* ptr_yy_globals )

{
    struct yyguts_t dummy_yyguts;

    yyset_extra (yy_user_defined, &dummy_yyguts);

    if (ptr_yy_globals == NULL){
        errno = EINVAL;
        return 1;
    }
	
    *ptr_yy_globals = (yyscan_t) yyalloc ( sizeof( struct yyguts_t ), &dummy_yyguts );
	
    if (*ptr_yy_globals == NULL){
        errno = ENOMEM;
        return 1;
    }
    
    /* By setting to 0xAA, we expose bugs in
    yy_init_globals. Leave at 0x00 for releases. */
    memset(*ptr_yy_globals,0x00,sizeof(struct yyguts_t));
    
    yyset_extra (yy_user_defined, *ptr_yy_globals);
    
    return yy_init_globals ( *ptr_yy_globals );
}

static int yy_init_globals (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;
    /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    yyg->yy_buffer_stack = 0;
    yyg->yy_buffer_stack_top = 0;
    yyg->yy_buffer_stack_max = 0;
    yyg->yy_c_buf_p = (char *) 0;
    yyg->yy_init = 0;
    yyg->yy_start = 0;

    yyg->yy_start_stack_ptr = 0;
    yyg->yy_start_stack_depth = 0;
    yyg->yy_start_stack =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (yyscan_t yyscanner)
{
    struct yyguts_t * yyg = (struct yyguts_t*)yyscanner;

    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER ,yyscanner );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state(yyscanner);
	}

	/* Destroy the stack itself. */
	yyfree(yyg->yy_buffer_stack ,yyscanner);
	yyg->yy_buffer_stack = NULL;

    /* Destroy the start condition stack. */
        yyfree(yyg->yy_start_stack ,yyscanner );
        yyg->yy_start_stack = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( yyscanner);

    /* Destroy the main struct (reentrant only). */
    yyfree ( yyscanner , yyscanner );
    yyscanner = NULL;
    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n , yyscan_t yyscanner)
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s , yyscan_t yyscanner)
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size , yyscan_t yyscanner)
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size , yyscan_t yyscanner)
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr , yyscan_t yyscanner)
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 399 "gibbon-gmd-lexer.l"



